### ISSUE TITLE
XAML Designer for UWP broken after extension update

### ISSUE THREAD

**Issue by vinderguy** [microsoft/cppwinrt#981]
Since I've updated the **C++/WinRT VSIX extension** to version **2.0.210709.3** I am unable to use the **XAML Designer** for **Blank Page** and **Blank User Control** items. This issue applies only to new and existing **C++/WinRT Blank App** projects. The XAML Designer works normally for C# UWP apps.

[This problem on Visual Studio Developer Community](https://developercommunity2.visualstudio.com/t/CWinRT-XAML-Designer:-SystemArgument/1472205?space=8&q=C%2B%2B%2FWinRT+designer)

![image](https://user-images.githubusercontent.com/26736457/125348826-05944980-e35d-11eb-97db-2933b63cf581.png)

<details>
System.ArgumentNullException
Value cannot be null.
Parameter name: path1
   at System.IO.Path.Combine(String path1, String path2)
   at Microsoft.VisualStudio.DesignTools.UwpDesignerHost.ShadowCopy.AppxRecipeShadowCopyWorker.Initialize(IHostPlatform platform, IHostProject hostProject, IAppPackageHelper appPackageHelper, SurfaceProcessInfo surfaceInfo, IHostTelemetryService hostTelemetry)
   at Microsoft.VisualStudio.DesignTools.UwpDesignerHost.ShadowCopy.AppxNativeShadowCopyWorker.Initialize(IHostPlatform platform, IHostProject hostProject, IAppPackageHelper appPackageHelper, SurfaceProcessInfo surfaceInfo, IHostTelemetryService hostTelemetry)
   at Microsoft.VisualStudio.DesignTools.UwpDesignerHost.ShadowCopy.UwpShadowCopyWorkerFactory.CreateWorker(SurfaceProcessInfo surfaceProcessInfo, IHostProject hostProject, IHostTelemetryService hostTelemetryService)
   at Microsoft.VisualStudio.DesignTools.DesignerHost.HostServices.HostPlatformBase.CreateSurfaceProcessInfo(IHostProject hostProject, Boolean forcePlatformOnly)
   at Microsoft.VisualStudio.DesignTools.SurfaceDesigner.Documents.Project.ProjectContextBase.CreateSurfaceProcessInfo(Boolean forcePlatformOnly)
   at Microsoft.VisualStudio.DesignTools.SurfaceDesigner.Documents.SurfaceIsolation.SurfaceProcessContext.<EnsureSurfaceProcessAsyncCore>d__107.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.DesignTools.SurfaceDesigner.Documents.SurfaceIsolation.SurfaceProcessContext.<EnsureSurfaceProcessAsyncInternal>d__105.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.DesignTools.XamlSurfaceDesigner.Views.IsolatedSurfaceImageHost.<CreateSurfaceAsync>d__66.MoveNext()

System.AggregateException
One or more errors occurred.
</details>

**Things I've tried to fix it:**
- Reloading the designer in both modes
- Reinstalling the C++/WinRT VSIX extension
- Downgrading C++/WinRT NuGet package to a lower version
- Resetting Visual Studio 2019 settings to all collections (none worked)
- Reinstalling both Visual Studio 2019 and Visual Studio Installer
- Fresh installing the entire Windows 10 on my personal computer

I've also managed to **reproduce** the issue on a new **virtual machine**.

**The software I use:**
- Windows 10 Pro 21H1 (build **19043.1803**)
- Visual Studio **16.10.3**
- C++/WinRT VSIX extension **2.0.210709.3**
- C++/WinRT NuGet package **2.0.210709.3** (also happens on older versions)

That all may be possibly related to #979, but I can't determine the real cause. Feel free to ask me If you have any additional questions or trouble in reproducing the problem.

**Comment by kennykerr** [comment]
FYI @jlaanstra for msbuild changes / @DefaultRyan for vsix changes

**Comment by vinderguy** [comment]
I'd like to add that only the two latest versions of C++/WinRT NuGet package (v**2.0.210709.3** and v**2.0.210708.4**) are affected. If you downgrade to v**2.0.210707.1** or a lower version and reopen the Visual Studio 2019, the designer loads as it should.

**Comment by kennykerr** [comment]
Thanks! That isolates the regression to #977 / #979 - we can revert those changes if needed.

**Comment by jlaanstra** [comment]
Looking.

**Comment by kennykerr** [comment]
I just published version 2.0.210714.1 - I took a quick look and the Designer seems to be working again - thanks for the quick fix @jlaanstra!
